dist: xenial
sudo: require
language: cpp
compiler: clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-7
    packages:
      - cmake
      - clang-7
      - libc++-7-dev
      - libc++abi-7-dev
script:
  - export CC=clang-7
  - export CXX=clang++-7
  - export CXXFLAGS="-std=c++17 -stdlib=libc++"
  - export LDFLAGS="-stdlib=libc++"
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make cista-test
  - ./cista-test