dist: xenial
sudo: require
language: cpp
compiler: clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-7
    packages:
      - cmake
      - clang-7
      - libc++-7-dev
      - libc++abi-7-dev
env:
  - BUILD_TYPE=Release LDFLAGS="-stdlib=libc++" CC="clang-7" CXX="clang++-7" CXXFLAGS="-std=c++17 -stdlib=libc++ -D_LIBCPP_VERSION=1"
  - BUILD_TYPE=Debug   LDFLAGS="-stdlib=libc++" CC="clang-7" CXX="clang++-7" CXXFLAGS="-std=c++17 -stdlib=libc++ -D_LIBCPP_VERSION=1 -fno-omit-frame-pointer -fsanitize=address"
  - BUILD_TYPE=Release                          CC="gcc-6"   CXX="g++-6"     CXXFLAGS="-std=c++17"
  - BUILD_TYPE=Debug                            CC="gcc-6"   CXX="c++-6"     CXXFLAGS="-std=c++17 -fno-omit-frame-pointer -fsanitize=address"
script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make cista-format-check
  - make cista-test
  - ./cista-test
